version: "3"
services: 
    back-end:
        container_name: back-end
        volumes:
            - api:/apimodelos/shared/api
            - components:/apimodelos/shared/components
        build: 
            context: ./apiModelos
            dockerfile: ./Dockerfile
        restart: always
        ports: 
            - "4000:3000"
        links:
            - mongo
            - strapi
        networks:
            default:
              aliases:
                - front-end
    mongo:
        container_name: mongo
        environment:
            MONGO_INITDB_DATABASE: StrapiAPI
            MONGO_INITDB_DATABASE: LEI2021
        image: mongo
        ports: 
            - "27018:27017"
    front-end:
        container_name: front-end
        restart: always
        build:
            context: ./app
            dockerfile: ./Dockerfile
        ports: 
            - "8080:80"
        links:
            - back-end
            - strapi
        networks:
            default:
              aliases:
                - back-end
    strapi:
        image: strapi/strapi
        container_name: strapi
        build: 
            context: ./StrapiAPI
            dockerfile: ./Dockerfile
        volumes:
            - api:/StrapiAPI/api
            - components:/StrapiAPI/components
        environment:
            DATABASE_CLIENT: mongo
            DATABASE_NAME: StrapiAPI
            DATABASE_HOST: mongo
            DATABASE_PORT: 27017
        ports:
            - '1338:1337'
        depends_on:
            - mongo
volumes:
    api:
    components: