version: '3'
services:
    mongo:
        container_name: mongo2
        environment:
            MONGO_INITDB_DATABASE: StrapiAPI
            MONGO_INITDB_ROOT_USERNAME: strapi
            MONGO_INITDB_ROOT_PASSWORD: strapi
        image: mongo
        ports: 
            - "27018:27017"
    strapi:
        image: strapi/strapi
        build: 
            context: ./StrapiAPI
            dockerfile: ./Dockerfile
        environment:
          DATABASE_CLIENT: mongo
          DATABASE_NAME: StrapiAPI
          DATABASE_HOST: mongo
          DATABASE_PORT: 27017
          DATABASE_USERNAME: strapi
          DATABASE_PASSWORD: strapi
        ports:
          - '1337:1337'
        depends_on:
          - mongo